WITH BOOK_SALES_INFO AS (
    SELECT a.BOOK_ID, CATEGORY, AUTHOR_ID, PRICE, SALES
    FROM BOOK_SALES a INNER JOIN BOOK b ON a.BOOK_ID = b.BOOK_ID
    WHERE YEAR(SALES_DATE) = 2022 and MONTH(SALES_DATE) = 1
)

SELECT a.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) as 'TOTAL_SALES'
FROM BOOK_SALES_INFO a JOIN AUTHOR b ON a.AUTHOR_ID = b.AUTHOR_ID
GROUP BY a.AUTHOR_ID, a.CATEGORY
ORDER BY 1, 3 DESC