-- 코드를 입력하세요
# SELECT b.AUTHOR_ID, b.AUTHOR_NAME, CATEGORY, (price*cnt) TOTAL_SALES
# FROM BOOK a INNER JOIN AUTHOR b INNER JOIN 

# (SELECT BOOK_ID, count(*) cnt 
# FROM BOOK_SALES 
# WHERE month(SALES_DATE)=1  
# GROUP BY BOOK_ID) c on a.BOOK_ID= c.BOOK_ID and a.AUTHOR_ID=b.AUTHOR_ID
# ORDER BY AUTHOR_ID, CATEGORY DESC;

SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * bs.SALES) AS TOTAL_SALES
FROM BOOK_SALES bs JOIN BOOK b on bs.BOOK_ID = b.BOOK_ID
                   JOIN AUTHOR a on b.AUTHOR_ID = a.AUTHOR_ID
WHERE month(bs.SALES_DATE)=1  
GROUP BY a.AUTHOR_NAME, b.CATEGORY
ORDER BY a.AUTHOR_ID ASC, b.CATEGORY DESC; 