WITH yogurt as (SELECT DISTINCT(CART_ID) FROM CART_PRODUCTS WHERE NAME = 'Yogurt')

SELECT 
    a.CART_ID
FROM 
    yogurt a INNER JOIN (SELECT DISTINCT(CART_ID) FROM CART_PRODUCTS WHERE NAME = 'Milk') b ON a.CART_ID = b.CART_ID
ORDER BY 1