-- 코드를 입력하세요
SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, '%Y-%m-%d'), 
CASE
WHEN OUT_DATE is NULL THEN '출고미정'
WHEN TIMESTAMPDIFF(DAY, OUT_DATE, '2022-05-01') >= 0 THEN '출고완료' 
WHEN TIMESTAMPDIFF(DAY, OUT_DATE, '2022-05-01') < 0 THEN '출고대기' 
END 출고여부
FROM FOOD_ORDER
ORDER BY ORDER_ID; 

# SELECT TIMESTAMPDIFF(DAY, OUT_DATE, '2022-05-01'), OUT_DATE FROM FOOD_ORDER; 