-- 코드를 입력하세요
# SELECT DISTINCT car_id
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE NOT (end_date < '2022-11-01' || start_date > '2022-11-30')


/*
    CAR_RENTAL_COMPANY_CAR : 자동차 정보
    CAR_RENTAL_COMPANY_RENTAL_HISTORY : 대여 기록
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN : 할인 정책
*/

# 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE)
SELECT a.CAR_ID, a.CAR_TYPE, 
    ROUND((a.DAILY_FEE - (a.DAILY_FEE*((SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = a.CAR_TYPE AND DURATION_TYPE LIKE '30%')) / 100) ) * 30,0) 'FEE'
FROM CAR_RENTAL_COMPANY_CAR a 
WHERE a.CAR_TYPE IN ('세단', 'SUV') AND 
    a.CAR_ID NOT IN (
        SELECT DISTINCT car_id
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE NOT (end_date < '2022-11-01' || start_date > '2022-11-30')    
    ) 
    AND
     (a.DAILY_FEE - (a.DAILY_FEE*((SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = a.CAR_TYPE AND DURATION_TYPE LIKE '30%')) / 100) ) * 30  BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, a.CAR_TYPE, a.CAR_ID DESC

# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b ON a.CAR_ID = b.CAR_ID
    
    # SELECT (a.DAILY_FEE - (a.DAILY_FEE*((SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = a.CAR_TYPE AND DURATION_TYPE LIKE '30%')) / 100) ) * 30
    # FROM CAR_RENTAL_COMPANY_CAR a
    
    # SELECT DAILY_FEE
    # FROM CAR_RENTAL_COMPANY_CAR
    

    
    