-- 코드를 입력하세요
WITH TBL as(
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

# SELECT * FROM REST_INFO

SELECT FOOD_TYPE,	REST_ID,	REST_NAME,	FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (SELECT FOOD_TYPE, FAVORITES FROM TBL)
ORDER BY 1 DESC