-- 코드를 입력하세요
SELECT a.ANIMAL_ID, a.ANIMAL_TYPE,	a.NAME 
FROM ANIMAL_INS a JOIN ANIMAL_OUTS b on a.ANIMAL_ID = b.ANIMAL_ID
WHERE SEX_UPON_INTAKE like 'Intact%' AND (SEX_UPON_OUTCOME like 'Neutered%' OR SEX_UPON_OUTCOME like 'Spayed%'); 