-- 코드를 입력하세요
SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS i INNER JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE SEX_UPON_INTAKE like "Intact%" AND (SEX_UPON_OUTCOME like "Spayed%" OR SEX_UPON_OUTCOME like "Neutered%")
ORDER BY 1