-- 코드를 입력하세요
SELECT YEAR(sales_date) YEAR, MONTH(sales_date) MONTH, GENDER, COUNT(DISTINCT a.USER_ID) USERS
FROM USER_INFO a INNER JOIN ONLINE_SALE b ON a.USER_ID = b.USER_ID
WHERE GENDER is NOT NULL
GROUP BY YEAR(sales_date), MONTH(sales_date), GENDER
ORDER BY 1, 2, 3