-- 코드를 입력하세요
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS
# , FREEZER_YN
, CASE 
    WHEN FREEZER_YN is NULL THEN 'N'
    WHEN FREEZER_YN = 'N' THEN 'N'
    WHEN FREEZER_YN = 'Y' THEN 'Y'
END
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID;