-- 실패코드 : 문자열로 가공된 뒤 데이터 정렬은 원하는 결과가 안나올 수 있다.

SELECT 
    ROUTE, CONCAT(ROUND(MAX(D_CUMULATIVE)/10, 1), 'km') as TOTAL_DISTANCE, CONCAT(ROUND(AVG(D_BETWEEN_DIST),2), 'km') as AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY TOTAL_DISTANCE DESC

-- 문자열로 바꾸기 전 숫자 데이터를 가지고 order by 할 것!

SELECT 
    ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') as TOTAL_DISTANCE, CONCAT(ROUND(AVG(D_BETWEEN_DIST),2), 'km') as AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUND(SUM(D_BETWEEN_DIST), 1) DESC
