# -- 코드를 입력하세요
SELECT YEAR(b.SALES_DATE) 'YEAR', MONTH(b.SALES_DATE) 'MONTH', COUNT(DISTINCT a.USER_ID) 'PURCHASED_USERS',
    ROUND((COUNT(DISTINCT a.USER_ID)/(SELECT 
    COUNT(*)
FROM 
    USER_INFO
WHERE 
    YEAR(JOINED) = 2021)), 1) 'PUCHASED_RATIO'
FROM USER_INFO a JOIN ONLINE_SALE b ON a.USER_ID = b.USER_ID
WHERE YEAR(a.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH

# SELECT DATE_FORMAT(O.SALES_DATE, '%Y') AS YEAR,
#         DATE_FORMAT(O.SALES_DATE, '%m') AS MONTH,
#         COUNT(DISTINCT U.USER_ID) AS PUCHASED_USERS,
#         ROUND(COUNT(DISTINCT U.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE joined LIKE '2021%'), 1) AS PUCHASED_RATIO
# FROM USER_INFO U
# JOIN ONLINE_SALE O
# ON U.USER_ID = O.USER_ID
# WHERE U.JOINED LIKE '2021%'
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH
# ;