
WITH availability as (
    SELECT CAR_ID, START_DATE, END_DATE,
    CASE 
        WHEN START_DATE <= '2022-10-16' and END_DATE >= '2022-10-16' THEN '대여중'
        ELSE '대여 가능'
    END as AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ORDER BY CAR_ID DESC
)

SELECT CAR_ID,
    CASE 
        WHEN CAR_ID IN (SELECT CAR_ID FROM availability WHERE AVAILABILITY = '대여중') THEN '대여중'
        ELSE '대여 가능'
    END as AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY 1 DESC