-- 코드를 작성해주세요
WITH QUARTER AS(
    SELECT ID, CASE
            WHEN MONTH(DIFFERENTIATION_DATE) IN (1, 2, 3) THEN '1Q'
            WHEN MONTH(DIFFERENTIATION_DATE) IN (4, 5, 6) THEN '2Q'
            WHEN MONTH(DIFFERENTIATION_DATE) IN (7, 8, 9) THEN '3Q'
            WHEN MONTH(DIFFERENTIATION_DATE) IN (10, 11, 12) THEN '4Q'
        END 'Q'
    FROM ECOLI_DATA
)

SELECT b.Q 'QUARTER', COUNT(b.Q) 'ECOLI_COUNT'
FROM ECOLI_DATA a JOIN QUARTER b ON a.ID = b.ID
GROUP BY b.Q
ORDER BY 1