-- 코드를 입력하세요
SELECT a.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT) * PRICE as TOTAL_SALES
FROM FOOD_ORDER a INNER JOIN FOOD_PRODUCT b ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 and MONTH(PRODUCE_DATE) = 5
GROUP BY a.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC