-- 코드를 입력하세요
# SELECT *
# FROM FIRST_HALF as a JOIN JULY as b

# SELECT *
# FROM FIRST_HALF

WITH HALF_TOTAL_ORDER as (
    SELECT FLAVOR HF, SUM(TOTAL_ORDER) HTO
    FROM FIRST_HALF
    GROUP BY FLAVOR
)
,
JULY_TOTAL_ORDER as (
    SELECT FLAVOR JF, SUM(TOTAL_ORDER) JTO
    FROM JULY
    GROUP BY FLAVOR
)
,
UNTIL_JULY_TOTAL_ORDER as (
    SELECT *
    FROM HALF_TOTAL_ORDER a LEFT OUTER JOIN JULY_TOTAL_ORDER b ON a.HF = b.JF

    UNION

    SELECT *
    FROM HALF_TOTAL_ORDER a RIGHT OUTER JOIN JULY_TOTAL_ORDER b ON a.HF = b.JF
)


SELECT HF
FROM UNTIL_JULY_TOTAL_ORDER
ORDER BY (HTO + JTO) DESC
LIMIT 3
