/*
    아이스크림 가게의 상반기 주문 정보를 담은 FIRST_HALF
    7월의 아이스크림 주문 정보를 담은 JULY
*/
WITH JULY_TOTAL as (
    SELECT FLAVOR, SUM(TOTAL_ORDER) 'TOTAL'
    FROM JULY
    GROUP BY FLAVOR
)

SELECT a.FLAVOR
FROM FIRST_HALF a JOIN JULY_TOTAL b ON a.FLAVOR = b.FLAVOR
ORDER BY (a.TOTAL_ORDER + b.TOTAL) DESC
LIMIT 3