-- 코드를 입력하세요
SELECT a.APNT_NO,p.PT_NAME,	p.PT_NO,	a.MCDP_CD, 	d.DR_NAME,	a.APNT_YMD
FROM APPOINTMENT a, PATIENT p, DOCTOR d 
WHERE a.PT_NO = p.PT_NO and a.MDDR_ID = d.DR_ID
    and SUBSTR(APNT_YMD,1,10)='2022-04-13' and APNT_CNCL_YN = 'N' and a.MCDP_CD='CS'
ORDER BY APNT_YMD; 