-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, a.TOTAL_SALES
FROM (SELECT WRITER_ID, sum(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING sum(PRICE) >= 700000) a INNER JOIN USED_GOODS_USER b on a.WRITER_ID = b.USER_ID
ORDER BY a.TOTAL_SALES;