-- 코드를 입력하세요
WITH MORE_THAN_FIVE AS (
    SELECT CAR_ID, COUNT(CAR_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) IN (8, 9, 10) AND YEAR(START_DATE) = 2022
    GROUP BY CAR_ID
        HAVING COUNT(CAR_ID) >= 5
)

SELECT MONTH(a.START_DATE), a.CAR_ID, COUNT(a.CAR_ID) 'RECORDS'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a JOIN MORE_THAN_FIVE b ON a.CAR_ID = b.CAR_ID
WHERE MONTH(START_DATE) IN (8, 9, 10) AND YEAR(START_DATE) = 2022
GROUP BY a.CAR_ID, MONTH(a.START_DATE)
    # HAVING COUNT(a.CAR_ID) >= 1
ORDER BY 1, 2 DESC