-- 코드를 입력하세요
SELECT MONTH(START_DATE) as MONTH, car_id as CAR_ID, COUNT(HISTORY_ID) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE car_id in (
    SELECT car_id
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022 and MONTH(START_DATE) >= 8 and MONTH(START_DATE) <= 10
    GROUP BY car_id
    HAVING COUNT(car_id) >= 5
)
AND YEAR(START_DATE) = 2022 and MONTH(START_DATE) >= 8 and MONTH(START_DATE) <= 10
GROUP BY MONTH(START_DATE), car_id
# HAVING COUNT(HISTORY_ID) > 0
ORDER BY 1 ASC, 2 DESC