-- 코드를 작성해주세요

WITH MS AS (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
),

A AS(
    SELECT *, YEAR(DIFFERENTIATION_DATE) YEAR
    FROM ECOLI_DATA
)

SELECT a.YEAR, (MAX_SIZE-SIZE_OF_COLONY) AS 'YEAR_DEV', ID
FROM A a JOIN MS b ON a.YEAR = b.YEAR
ORDER BY 1, 2