-- 코드를 작성해주세요
WITH GRADE as (
    SELECT EMP_NO, SUM(SCORE) 'SCORE'
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT SCORE, a.EMP_NO, EMP_NAME, POSITION, EMAIL 
FROM HR_EMPLOYEES a INNER JOIN GRADE b ON a.EMP_NO = b.EMP_NO
ORDER BY SCORE DESC
LIMIT 1