-- 코드를 입력하세요
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) 'TOTAL_ORDER'
FROM FIRST_HALF a INNER JOIN ICECREAM_INFO b ON a.FLAVOR = b.FLAVOR
GROUP BY b.INGREDIENT_TYPE
ORDER BY 2 

# SELECT *
# FROM FIRST_HALF a INNER JOIN ICECREAM_INFO b 