-- 코드를 입력하세요
select INGREDIENT_TYPE ,sum(TOTAL_ORDER) TOTAL_ORDER
from FIRST_HALF Left outer join ICECREAM_INFO on FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
group by INGREDIENT_TYPE
order by TOTAL_ORDER asc;

# select * from FIRST_HALF  Left outer join ICECREAM_INFO on FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR; 