-- 코드를 입력하세요
# 게시물 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일

SELECT A.TITLE,	A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, 	DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as A inner join USED_GOODS_REPLY as B on A.BOARD_ID = B.BOARD_ID
WHERE YEAR(A.CREATED_DATE) = 2022 and MONTH(A.CREATED_DATE) = 10
ORDER BY B.CREATED_DATE, A.TITLE	