-- 코드를 입력하세요
# WITH MAX_VIES (
    # SELECT BOARD_ID 
    # FROM USED_GOODS_BOARD 
    # WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
# )

SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) 'FILE_PATH'
FROM USED_GOODS_FILE
WHERE BOARD_ID IN (SELECT BOARD_ID 
    FROM USED_GOODS_BOARD 
    WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD))
ORDER BY FILE_ID DESC

