-- 코드를 입력하세요
SELECT concat('/home/grep/src/', BOARD_ID, '/', FILE_ID,FILE_NAME , FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID = (select BOARD_ID from USED_GOODS_BOARD ORDER BY VIEWS DESC limit 1)
ORDER BY FILE_ID DESC; 


# select * FROM USED_GOODS_FILE WHERE BOARD_ID = 'B0008'; 
