-- 코드를 입력하세요
WITH RANKING as (
    SELECT *, RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) as 'RANK_NUM'
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)

SELECT CATEGORY, PRICE as 'MAX_PRICE', PRODUCT_NAME
FROM RANKING
WHERE RANK_NUM = 1
ORDER BY 2 DESC