-- 코드를 입력하세요
WITH EXPENSIVE as ( 
    SELECT CATEGORY, MAX(PRICE) 'PRICE'
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)

SELECT a.CATEGORY, a.PRICE	'MAX_PRICE', 	a.PRODUCT_NAME
# SELECT *
FROM FOOD_PRODUCT a JOIN EXPENSIVE b ON a.CATEGORY = b.CATEGORY AND a.PRICE = b.PRICE
ORDER BY 2 DESC 

# SELECT * FROM FOOD_PRODUCT WHERE CATEGORY = '과자' ORDER BY PRICE DESC
# SELECT * FROM EXPENSIVE
