-- 코드를 작성해주세요
SELECT
    COUNT(FISH_TYPE) as 'FISH_COUNT', MAX(LENGTH) as 'MAX_LENGTH', FISH_TYPE
FROM 
 (SELECT ID, FISH_TYPE, TIME,  IFNULL(LENGTH, 10) as 'LENGTH' FROM FISH_INFO) a
GROUP BY 
    FISH_TYPE
HAVING
    AVG(LENGTH) >= 33
ORDER BY 
    3