-- 코드를 입력하세요
# SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d')  PUBLISHED_DATE
# FROM BOOK a JOIN AUTHOR b on a.AUTHOR_ID = b.AUTHOR_ID
# where a.category = '경제';

SELECT A.BOOK_ID, B.AUTHOR_NAME, DATE_FORMAT(A.PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
FROM 
(SELECT *
 FROM BOOK
 WHERE CATEGORY='경제')A
JOIN AUTHOR B
ON A.AUTHOR_ID=B.AUTHOR_ID
ORDER BY A.PUBLISHED_DATE ASC;