-- 코드를 입력하세요
with PG as (
    SELECT *, 
    (TRUNCATE(PRICE / 10000, 0)) * 10000 as PRICE_GROUP
    FROM PRODUCT
)

SELECT PRICE_GROUP, COUNT(PRICE_GROUP) PRODUCTS
FROM PG
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP ASC

# SELECT * FROM PRODUCT